id = "hyprlang"
name = "Hyprlang"
version = "0.0.4"
schema_version = 1
authors = ["WhySoBad <git@wysbd.dev>"]
description = "Hyprlang language server and syntax highlighting"
repository = "https://github.com/WhySoBad/zed-hyprlang-extension"

[language_servers.hyprland]
name = "hyprls"
language = "Hyprland Config"

[grammars.hyprlang]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-hyprlang"
commit = "22723f25f3faf329863d952c9601b492afd971c9"
