id = "hyprlang"
name = "Hyprlang"
version = "0.0.3"
schema_version = 1
authors = ["WhySoBad <git@wysbd.dev>"]
description = "Hyprlang language server and syntax highlighting"
repository = "https://github.com/WhySoBad/zed-hyprlang-extension"

[language_servers.hyprland]
name = "hyprls"
language = "Hyprland Config"

[grammars.hyprlang]
repository = "https://github.com/whysobad/tree-sitter-hyprlang"
commit = "a12160b9fd074305c2a84296713816ae2932a99c"
